export { default as Dashboard } from './dashboard/Dashboard';
export { default as Classroom } from './classroom/Classroom';
export { default as ClassroomDetails } from './classroom/ClassroomDetails';
export { default as Teaching } from './teaching/Teaching';
export { default as TeachingDetails } from './teaching/TeachingDetails';
export { default as Course } from './course/Course';
export { default as CourseDetails } from './course/CourseDetails';
export { default as Layout } from './layout/Layout';
export { default as NoPage } from './nopage/NoPage';